
const STATUS_OK = 200;
const STATUS_CREATED = 201;
const ERROR_INCORRECT_DATA = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;

module.exports = {
  STATUS_OK, STATUS_CREATED, ERROR_INCORRECT_DATA , ERROR_NOT_FOUND, ERROR_DEFAULT
}